[Draft] Respect max-age header of public keys response
Nickforall/ExFirebaseAuth pull request #20
Opened 2021-05-04 03:27 UTC by lucasavila00

I'm not sure if this is the best way to parse the tokens, I just copied the code from https://github.com/firebase/firebase-admin-go/blob/master/auth/token_verifier.go

And I just realized I based this branch on my other PR.

Anyway, I wouldn't mind this PR being closed in favor of a better one that does the same thing, and I'd be thrilled to know what the proper code would look like :smile:

2021-05-04 09:39 UTC, Nickforall commented
Woah this is awesome, I'll do a more in-depth review of this later when I have more time later this week.

2021-05-04 09:53 UTC, Nickforall requested changes
Looks good, some small comments but nice work!

2021-05-04 09:53 UTC, Nickforall commented on lib/source/google_key_source.ex
> +  defp get_get_max_age_from_cache_control(nil) do
It looks like you made a small typo here

```suggestion
  defp get_max_age_from_cache_control(nil) do
```

2021-05-04 09:53 UTC, Nickforall commented on lib/source/google_key_source.ex
> +    Enum.find_value(values, fn x ->
`Enum.find_value/2` returns a default, which is currently nil but I think we should make that 300 as well (https://hexdocs.pm/elixir/Enum.html#find_value/3)

https://hexdocs.pm/elixir/Enum.html#find_value/3

2021-05-07 00:21 UTC, lucasavila00 commented
I want to re-do this PR from scratch. I'll try do it tomorrow.

2021-05-07 00:29 UTC, Nickforall commented
Sure thing! No worries :)

2022-01-04 11:09 UTC, Nickforall commented
Closing this as stale

2022-01-04 11:09 UTC, closed without merging